language: node_js
node_js: 8

before_script:
  - npm install firebase-tools -g
  - cd functions && npm install

script:
  - firebase deploy --only functions --token "1//0cRvI7EcggQcZCgYIARAAGAwSNwF-L9IrexL70ETq6bCpcIUgXEKJNRs6rdAAp7yzMcZ-n_KEmFp25BNDeGdxfr0JkU2ZKLVIeH0"